"""use new models Page and User

Revision ID: 742f7a72998f
Revises: 291720f72d43
Create Date: 2021-03-27 05:08:54.510640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742f7a72998f'
down_revision = '291720f72d43'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
