"""use new models Page and User

Revision ID: effed4732e6f
Revises: 742f7a72998f
Create Date: 2021-03-27 21:33:21.952797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effed4732e6f'
down_revision = '742f7a72998f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
